from setuptools import setup, find_packages
import os

# Read the long description from README.md
with open('README.md', encoding='utf-8') as f:
    long_description = f.read()

setup(
    name="careframe",
    version="0.1.0",
    author="CareFrame Contributors",
    author_email="example@example.com",
    description="An integrated research and clinical data platform",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/CareFrameAI/careframe-research",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Healthcare Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.9",
    install_requires=[
        'Pillow',
        'PyQt6',
        'SQLAlchemy',
        'aiohttp',
        'anthropic',
        'arviz',
        'better-profanity',
        'biopython',
        'cairosvg',
        'couchdb',
        'cryptography',
        'faiss-cpu',
        'fastapi',
        'google-generativeai',
        'habanero',
        'icd10',
        'lifelines',
        'lxml',
        'matplotlib',
        'networkx',
        'nltk',
        'numpy',
        'pandas',
        'pingouin',
        'presidio-analyzer',
        'presidio-anonymizer',
        'psutil',
        'pydantic',
        'pymc',
        'pyqtgraph',
        'pyspellchecker',
        'python-dotenv',
        'qasync',
        'qt-material',
        'rank-bm25',
        'requests',
        'scikit-learn',
        'scikit-posthocs',
        'scipy',
        'scispacy',
        'scrubadub',
        'seaborn',
        'sentence-transformers',
        'spacy',
        'statsmodels',
        'uvicorn',
        'websockets',
    ],
    entry_points={
        "console_scripts": [
            "careframe=app:initialize_app",
        ],
    },
    include_package_data=True,
) 